#!/usr/bin/env python3
"""
install_hooks.py - Install git hooks for burndown-chart.

Writes pre-commit, pre-push, and post-merge hooks into .git/hooks/.
Run once after cloning or whenever hooks need refreshing.

Usage:
    python install_hooks.py          # install hooks
    python install_hooks.py --check  # report what would change without writing
    python install_hooks.py --force  # overwrite existing hooks without prompting

Platform-agnostic: works on Windows, macOS, and Linux.

Hook behavior installed:
    pre-commit         - ruff lint + format check (~5s).  Runs on every `git commit`.
    commit-msg         - validates conventional commit format with bead ID trailer.
    pre-push           - full quality gate via validate.py.  Runs on `git push`.
    post-merge         - re-runs install_hooks.py after every `git pull` so hooks
                         stay current for all developers automatically.
    post-checkout      - beads branch-tracking on checkout.
    prepare-commit-msg - beads agent identity trailers for AI audit forensics.

The hooks delegate to bd (beads) if available, then always run the Python
quality checks so CI enforcement holds even without the bd tool.
"""

import argparse
import platform
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).parent
HOOKS_DIR = ROOT / ".git" / "hooks"

# ---------------------------------------------------------------------------
# Hook content templates.
# Git calls hooks with #!/usr/bin/env sh which git bundles on all platforms
# (Git for Windows provides sh.exe).  The sh script detects the venv Python
# cross-platform and delegates to validate.py so logic stays in Python.
# ---------------------------------------------------------------------------

_PYTHON_DETECT = """\
# Locate the venv Python interpreter (cross-platform).
if [ -f ".venv/Scripts/python.exe" ]; then
    PYTHON=".venv/Scripts/python.exe"   # Windows (Git for Windows sh)
elif [ -f ".venv/bin/python" ]; then
    PYTHON=".venv/bin/python"           # macOS / Linux
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="python3"                    # system fallback
elif command -v python >/dev/null 2>&1; then
    PYTHON="python"                     # system fallback (older installs)
else
    echo "[git-hook] WARNING: Python not found; skipping quality checks." >&2
    exit 0
fi\
"""

_BD_CALL_PRECOMMIT = """\
# Run beads tracking hook if bd is installed.
if command -v bd >/dev/null 2>&1; then
    export BD_GIT_HOOK=1
    bd hooks run pre-commit "$@"
    _bd_exit=$?
    if [ "$_bd_exit" -eq 3 ]; then _bd_exit=0; fi
    if [ "$_bd_exit" -ne 0 ]; then exit "$_bd_exit"; fi
fi\
"""

_BD_CALL_POSTMERGE = """\
# Run beads tracking hook if bd is installed.
if command -v bd >/dev/null 2>&1; then
    export BD_GIT_HOOK=1
    bd hooks run post-merge "$@"
    _bd_exit=$?
    if [ "$_bd_exit" -eq 3 ]; then _bd_exit=0; fi
    if [ "$_bd_exit" -ne 0 ]; then exit "$_bd_exit"; fi
fi\
"""

_BD_CALL_PREPUSH = """\
# Run beads tracking hook if bd is installed.
if command -v bd >/dev/null 2>&1; then
    export BD_GIT_HOOK=1
    bd hooks run pre-push "$@"
    _bd_exit=$?
    if [ "$_bd_exit" -eq 3 ]; then _bd_exit=0; fi
    if [ "$_bd_exit" -ne 0 ]; then exit "$_bd_exit"; fi
fi\
"""

_BD_CALL_POSTCHECKOUT = """\
# Run beads tracking hook if bd is installed.
if command -v bd >/dev/null 2>&1; then
    export BD_GIT_HOOK=1
    bd hooks run post-checkout "$@" || true
fi\
"""

_BD_CALL_PREPARECOMMITMSG = """\
# Run beads tracking hook if bd is installed.
if command -v bd >/dev/null 2>&1; then
    export BD_GIT_HOOK=1
    bd hooks run prepare-commit-msg "$@" || true
fi\
"""

PRE_COMMIT_HOOK = f"""\
#!/usr/bin/env sh
# burndown-chart pre-commit hook
# Generated by install_hooks.py - do not edit manually; re-run the script instead.
#
# Runs: ruff lint + ruff format check (~5s).
# To bypass in an emergency only: git commit --no-verify

{_BD_CALL_PRECOMMIT}

{_PYTHON_DETECT}

if [ ! -f "validate.py" ] || [ ! -d ".venv" ]; then
    exit 0  # Not a dev worktree (e.g. bd backup); skip.
fi

echo "[git-hook] pre-commit: running ruff checks..."
"$PYTHON" validate.py --commit
exit $?
"""

PRE_PUSH_HOOK = f"""\
#!/usr/bin/env sh
# burndown-chart pre-push hook
# Generated by install_hooks.py - do not edit manually; re-run the script instead.
#
# Runs: full quality gate (ruff, djlint, pyright, markdownlint, pytest).
# This protects the remote branch and other developers from broken code.
# To bypass in an emergency only: git push --no-verify

{_BD_CALL_PREPUSH}

{_PYTHON_DETECT}

if [ ! -f "validate.py" ] || [ ! -d ".venv" ]; then
    exit 0  # Not a dev worktree (e.g. bd backup); skip.
fi

echo "[git-hook] pre-push: running full quality gate..."
"$PYTHON" validate.py
exit $?
"""

POST_MERGE_HOOK = f"""\
#!/usr/bin/env sh
# burndown-chart post-merge hook
# Generated by install_hooks.py - do not edit manually; re-run the script instead.
#
# Runs after every `git pull` (merge).  Keeps git hooks current for all
# developers automatically whenever install_hooks.py changes in the repo.

{_BD_CALL_POSTMERGE}

{_PYTHON_DETECT}

echo "[git-hook] post-merge: refreshing git hooks..."
"$PYTHON" install_hooks.py --force
"""

POST_CHECKOUT_HOOK = f"""\
#!/usr/bin/env sh
# burndown-chart post-checkout hook
# Generated by install_hooks.py - do not edit manually; re-run the script instead.
#
# Notifies beads about branch changes for issue tracking context.

{_BD_CALL_POSTCHECKOUT}
exit 0
"""

PREPARE_COMMIT_MSG_HOOK = f"""\
#!/usr/bin/env sh
# burndown-chart prepare-commit-msg hook
# Generated by install_hooks.py - do not edit manually; re-run the script instead.
#
# Adds beads agent identity trailers for AI audit forensics.

{_BD_CALL_PREPARECOMMITMSG}
exit 0
"""

COMMIT_MSG_HOOK = """\
#!/usr/bin/env sh
# burndown-chart commit-msg hook
# Generated by install_hooks.py - do not edit manually; re-run the script instead.
#
# Enforces the conventional commit format with a bead ID trailer:
#   type(scope): description (burndown-chart-NNN)
#
# Valid bead ID patterns:
#   (burndown-chart-abc12)   -- full prefix format
#   (bd-123)                 -- short numeric format (legacy)
#
# Bypass in an emergency only: git commit --no-verify

COMMIT_MSG_FILE="$1"

# Skip if not in a dev worktree (e.g. bd backup export worktree has no .venv).
if [ ! -d ".venv" ]; then
    exit 0
fi

# Read the first non-comment, non-empty line of the commit message.
FIRST_LINE=$(grep -v '^#' "$COMMIT_MSG_FILE" | grep -v '^[[:space:]]*$' | head -n1)

# Skip merge commits, fixups, squashes, revert commits, and release tags.
case "$FIRST_LINE" in
    "Merge "*|"Revert "*|"fixup! "*|"squash! "*|"chore(release):"*)
        exit 0 ;;
esac

# Require the bead ID trailer: (burndown-chart-XYZ) or (bd-NNN)
if echo "$FIRST_LINE" | grep -qE '\\(burndown-chart-[a-z0-9]+\\)|\\(bd-[0-9]+\\)'; then
    exit 0
fi

# Reject with a helpful error message.
echo "" >&2
echo "[git-hook] commit-msg: missing bead ID in commit message." >&2
echo "" >&2
echo "  Required format:  type(scope): description (burndown-chart-NNN)" >&2
echo "  Examples:" >&2
echo "    feat(dashboard): add sprint burndown chart (burndown-chart-abc12)" >&2
echo "    fix(api): handle empty sprint response (bd-42)" >&2
echo "" >&2
echo "  Your message: $FIRST_LINE" >&2
echo "" >&2
echo "  To find your bead ID: bd ready --json" >&2
echo "  To bypass (emergency only): git commit --no-verify" >&2
echo "" >&2
exit 1
"""

HOOKS: dict[str, str] = {
    "pre-commit": PRE_COMMIT_HOOK,
    "commit-msg": COMMIT_MSG_HOOK,
    "pre-push": PRE_PUSH_HOOK,
    "post-merge": POST_MERGE_HOOK,
    "post-checkout": POST_CHECKOUT_HOOK,
    "prepare-commit-msg": PREPARE_COMMIT_MSG_HOOK,
}


def _make_executable(path: Path) -> None:
    """Add executable bits on Unix; no-op on Windows (git uses the shebang)."""
    if platform.system() != "Windows":
        current = path.stat().st_mode
        path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _content_differs(path: Path, expected: str) -> bool:
    if not path.exists():
        return True
    return path.read_text(encoding="utf-8") != expected


def install(check_only: bool = False, force: bool = False) -> int:
    if not HOOKS_DIR.exists():
        print(f"[install_hooks] ERROR: {HOOKS_DIR} not found.")
        print("[install_hooks] Run this script from the repository root.")
        return 1

    changes_needed: list[str] = []
    for name, content in HOOKS.items():
        hook_path = HOOKS_DIR / name
        if _content_differs(hook_path, content):
            changes_needed.append(name)

    if not changes_needed:
        print("[install_hooks] All hooks are up to date.")
        return 0

    if check_only:
        print("[install_hooks] Hooks that need updating:")
        for name in changes_needed:
            print(f"  {name}")
        return 1

    for name in changes_needed:
        hook_path = HOOKS_DIR / name
        if hook_path.exists() and not force:
            existing = hook_path.read_text(encoding="utf-8")
            if "burndown-chart" not in existing and "bd-shim" not in existing:
                # Unknown hook content — ask before overwriting.
                answer = input(
                    f"[install_hooks] {name} exists with unknown "
                    "content. Overwrite? [y/N] "
                )
                if answer.strip().lower() != "y":
                    print(f"[install_hooks] Skipped {name}.")
                    continue

        hook_path.write_text(HOOKS[name], encoding="utf-8", newline="\n")
        _make_executable(hook_path)
        print(f"[install_hooks] Installed: {hook_path}")

    print("[install_hooks] Done. Hooks will run on the next commit/push.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Install burndown-chart git hooks")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report outdated hooks without writing files",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing hooks without prompting",
    )
    args = parser.parse_args()

    system = platform.system()
    print(f"[install_hooks] Platform: {system} | Root: {ROOT}")

    return install(check_only=args.check, force=args.force)


if __name__ == "__main__":
    sys.exit(main())
