openapi: 3.0.0
info:
  title: GitHub Releases API
  description: Contract for fetching release information and downloading updates
  version: 1.0.0

servers:
  - url: https://api.github.com
    description: GitHub REST API

paths:
  /repos/{owner}/{repo}/releases/latest:
    get:
      summary: Get Latest Release
      description: Fetch the most recent non-prerelease release
      operationId: getLatestRelease
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
          example: "user"
        - name: repo
          in: path
          required: true
          schema:
            type: string
          example: "burndown-chart"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Release"
        "404":
          description: Repository not found or no releases published
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Release:
      type: object
      required:
        - tag_name
        - name
        - published_at
        - assets
      properties:
        tag_name:
          type: string
          description: Git tag name (e.g., "v2.5.0")
          example: "v2.6.0"
        name:
          type: string
          description: Release title
          example: "Burndown Chart v2.6.0"
        body:
          type: string
          description: Release notes (markdown format)
          example: |
            ## What's New
            - Feature: Standalone executable packaging
            - Bug fix: Database migration improvements
        published_at:
          type: string
          format: date-time
          description: Release publication timestamp (ISO 8601)
          example: "2026-01-20T10:30:00Z"
        prerelease:
          type: boolean
          description: Whether this is a pre-release version
          example: false
        draft:
          type: boolean
          description: Whether this is a draft release
          example: false
        html_url:
          type: string
          format: uri
          description: URL to release page
          example: "https://github.com/user/burndown-chart/releases/tag/v2.6.0"
        assets:
          type: array
          description: Downloadable release assets
          items:
            $ref: "#/components/schemas/Asset"

    Asset:
      type: object
      required:
        - name
        - browser_download_url
        - size
        - content_type
      properties:
        name:
          type: string
          description: Filename of the asset
          example: "burndown-chart-windows-v2.6.0.zip"
        browser_download_url:
          type: string
          format: uri
          description: Direct download URL
          example: "https://github.com/user/burndown-chart/releases/download/v2.6.0/burndown-chart-windows-v2.6.0.zip"
        size:
          type: integer
          description: File size in bytes
          example: 95420160
          minimum: 0
        content_type:
          type: string
          description: MIME type of the asset
          example: "application/zip"
        state:
          type: string
          enum: [uploaded]
          description: Upload state (always "uploaded" for published releases)
        created_at:
          type: string
          format: date-time
          description: Asset creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Asset last updated timestamp

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "Not Found"
        documentation_url:
          type: string
          format: uri
          description: Link to API documentation
          example: "https://docs.github.com/rest/releases/releases#get-the-latest-release"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: |
        Optional: GitHub personal access token for increased rate limits.
        Public repositories can be accessed without authentication (60 req/hour).
        With token: 5000 req/hour.

security:
  - bearerAuth: []
  - {} # Allow unauthenticated requests

# Usage Notes:
# 1. Rate Limits:
#    - Unauthenticated: 60 requests/hour per IP
#    - Authenticated: 5000 requests/hour per token
#    - App checks once per launch (well within limits)
#
# 2. Filtering Assets:
#    - Filter assets array for: name.endsWith('.zip') && name.includes('windows')
#    - Expected filename pattern: burndown-chart-windows-v{version}.zip
#
# 3. Version Comparison:
#    - Parse tag_name (strip 'v' prefix)
#    - Compare using semantic versioning (e.g., 2.6.0 > 2.5.0)
#    - Ignore prerelease versions (prerelease: true)
#
# 4. Error Handling:
#    - 404: No releases published or repo not found → silent fail, retry next launch
#    - Network timeout (>2s): Cancel check, retry next launch
#    - Invalid JSON: Log error, retry next launch
#
# 5. Cache Strategy:
#    - Check on every app launch
#    - No persistent cache (always fresh check)
#    - Timeout: 2 seconds max for non-blocking UX
